### ISSUE TITLE
Sign on is not reflecting on all SP's

### ISSUE THREAD

**Issue by IbrahimMuhaisen96** [codegreencreative/laravel-samlidp#47]
I have two SP's, when singing on, only one does, when logging out all of them does. I think it supposed to login across all SSO infrastructure

**Comment by upwebdesign** [comment]
@IbrahimMuhaisen96 we don't want to log in across all SP's, only the one we are trying to get access to. I had not thought about this much however. Could it be convenient to log in everywhere... maybe. Since the SP wont allow you to access their content without authorization, there really is no need to login at that SP unless we are intending to log in to that SP explicitly. During the logout process, we need to log out everywhere because we don't keep track of login sessions at the SP. It would be impossible to know if the user was actually logged in to any given SP.
